name: build on debian
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4'
          cabal-version: '3.0.0.0' # Exact version of Cabal      - 
      - name: install hdf5
        run: sudo apt-get install -y libhdf5-dev
      - name: build with cabal
        run: cabal build
