name: build and test on debian
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # 9.2 is broken with libfii7 and ubuntu, see
        # https://discourse.haskell.org/t/building-a-haskell-project-with-github-workflows-fails-with-libffi-error-only-on-ghc-9-2/10031/3
        ghc: ['9.6', '9.4']
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.0.0.0' # Exact version of Cabal      - 
      - name: install hdf5
        run: sudo apt-get install -y libhdf5-dev libffi-dev
      - name: build and test with cabal
        run: cabal test
